#!/usr/bin/env python3

import sys

if __name__ == "__main__":
	if sys.argv[0] != "/usr/local/bin/brew":
		print("ERROR: ", sys.argv[0])
		sys.exit(1)

	if len(sys.argv) == 2:
		if sys.argv[1] == "update":
			print("Already up-to-date.")
			sys.exit(0)
		elif sys.argv[1] == "upgrade":
			sys.exit(0)
		elif sys.argv[1] == "--version":
			print("brew --version")
			sys.exit(0)
		else:
			print("ERROR: ", sys.argv[1])
			sys.exit(1)

	elif len(sys.argv) == 3:
		if sys.argv[1] == "list" and sys.argv[2] == "-1":
			print("brew list -1")
			sys.exit(0)
		elif sys.argv[1] == "cask" and sys.argv[2] == "upgrade":
			print("==> No Casks to upgrade")
			sys.exit(0)
		else:
			print("ERROR: ", sys.argv[1], sys.argv[2])
			sys.exit(1)

	else:
		print("ERROR:", sys.argv)
		sys.exit(1)
