#!/usr/bin/env python3

import sys

if __name__ == "__main__":
	if sys.argv[0] != "/usr/local/bin/freshclam":
		print("ERROR: ", sys.argv[0])
		sys.exit(1)

	if sys.argv[1] == "--version":
		sys.exit(0)

	if len(sys.argv) == 5:
		print("freshclam: refreshing...")
		sys.exit(0)
	else:
		print("ERROR:", sys.argv)
		sys.exit(1)
