import os

TEST_CONSTANTS_FILE = os.path.abspath(__file__)
TEST_DIR = os.path.dirname(TEST_CONSTANTS_FILE)
TEST_RESOURCES_DIR = TEST_DIR + "/tst.resources"


EXISTING_DIR = "dirs"
EXISTING_DIR_A = "dirs/a"
EXISTING_DIR_B = "dirs/b"
EXISTING_DIR_C = "dirs/c"
EXISTING_FILE  = "file.txt"
EXISTING_ARCHIVE = "archive.tar.gz"

NONEXISTENT_DIR = "new"
NONEXISTENT_FILE = "new.txt"
NONEXISTENT_ARCHIVE = "new.tar.gz"

GPG_FILE_KEYID_INVALID = "filetest.txt.ZZcQMwLA.gpg"
GPG_FILE_KEYID_NONEXISTENT = "filetest.txt.AAAABBBB.gpg"
GPG_FILE_INVALID_NAME = "file.txtAAAABBBB.gpg"
ENCRYPTED_FILE = "filetest.txt.4C7798F2.gpg"

KEY_ID = "4C7798F2"
INVALID_KEY_ID = "ZZcQMwLA"
NONEXISTENT_KEY_ID = "AAAABBBB"
KEY_FINGERPRINT = "83BD4EAB9B558BC994CDF7A3CAD0AE184C7798F2"
INVALID_KEY_FINGERPRINT = "83BD 4EAB 9B55 8BC9 94CD  F7A3 CAD0 AE18 4C77 98F2"

NON_PATH_LIKE_OBJECT = 1
EMPTY_STRING = ""
